-- Crear tabla SUBSCRIPTION_PLANS
DROP TABLE IF EXISTS SUBSCRIPTION_PLANS;
CREATE TABLE SUBSCRIPTION_PLANS (
ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(255) NOT NULL,
PRICE DOUBLE NOT NULL,
PRIMARY KEY (ID)
);

-- Crear tabla APP_USERS
DROP TABLE IF EXISTS APP_USERS;
CREATE TABLE APP_USERS (
ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(255) NOT NULL,
EMAIL VARCHAR(255) NOT NULL,
PHONE VARCHAR(255) NOT NULL,
SUBSCRIPTION_PLAN INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (SUBSCRIPTION_PLAN) REFERENCES SUBSCRIPTION_PLANS(ID)
);

-- Crear tabla SIGNED_MESSAGES
DROP TABLE IF EXISTS SIGNED_MESSAGES;
CREATE TABLE SIGNED_MESSAGES (
ID INT NOT NULL AUTO_INCREMENT,
USER_ID INT NOT NULL,
MESSAGE VARCHAR(255) NOT NULL,
TIMESTAMP TIMESTAMP NOT NULL,
CONVERSATION_ID INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (USER_ID) REFERENCES APP_USERS(ID)
);

-- Crear tabla UNSIGNED_MESSAGES
DROP TABLE IF EXISTS UNSIGNED_MESSAGES;
CREATE TABLE UNSIGNED_MESSAGES (
ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(255) NOT NULL,
EMAIL VARCHAR(255) NOT NULL,
MESSAGE VARCHAR(255) NOT NULL,
TIMESTAMP TIMESTAMP NOT NULL,
PRIMARY KEY (ID)
);

-- Crear tabla PORTFOLIOS
DROP TABLE IF EXISTS PORTFOLIOS;
CREATE TABLE PORTFOLIOS (
ID INT NOT NULL AUTO_INCREMENT,
USER_ID INT NOT NULL,
NAME VARCHAR(255) NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (USER_ID) REFERENCES APP_USERS(ID)
);

-- Crear tabla PORTFOLIO_MOVEMENTS
DROP TABLE IF EXISTS PORTFOLIO_MOVEMENTS;
CREATE TABLE PORTFOLIO_MOVEMENTS (
ID INT NOT NULL AUTO_INCREMENT,
PORTFOLIO_ID INT NOT NULL,
TICKER VARCHAR(255) NOT NULL,
QUANTITY INT NOT NULL,
PRICE DOUBLE NOT NULL,
DATE DATE NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (PORTFOLIO_ID) REFERENCES PORTFOLIOS(ID)
);